### ISSUE TITLE
Table 'maraichage.exportations'

### ISSUE THREAD

**Issue by MachinisteWeb** [hybris71/maraichage#2]
En me rendant sur la page `http://127.0.0.1:7000/catalogue/Tomate`

J'ai l'erreur suivante : 

```js
{ Error: ER_NO_SUCH_TABLE: Table 'maraichage.exportations' doesn't exist
    at Query.Sequence._packetToError (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\nodejs\test\maraichage\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at PoolConnection.query (C:\nodejs\test\maraichage\node_modules\mysql\lib\Connection.js:208:25)
    at Plante.publics.readAll (C:\nodejs\test\maraichage\models\connectors\plante.js:276:29)
    at C:\nodejs\test\maraichage\controllers\plante.js:357:30
    at Query._callback (C:\nodejs\test\maraichage\models\connectors\groupe.js:49:21)
    at Query.Sequence.end (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.EofPacket (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\sequences\Query.js:121:8)
    at Protocol._parsePacket (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Parser.js:75:12)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0 }
C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property '0' of undefined
    at Query._callback (C:\nodejs\test\maraichage\models\connectors\plante.js:280:21)
    at Query.Sequence.end (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (C:\nodejs\test\maraichage\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\nodejs\test\maraichage\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

Peux-tu m'aider ?

J'ai regarder dans le fichier `maraichage.sql`, je ne vois aucune trace de cette table. Peux-tu la fournir ?

**Comment by hybris71** [comment]
Salut ! 
Je viens de mettre à jour le fichier maraichage.sql.
Cela devrait résoudre le problème.

**Comment by MachinisteWeb** [comment]
C'est good ! Merci !

**Comment by MickaelMenet** [comment]
Ce projet n'est plus d'actu ? :)

**Comment by MachinisteWeb** [comment]
Il me semble que non. @hybris71 ?
